# Generated by Django 5.1.7 on 2025-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_userreference_remove_category_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreference',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
