# Generated by Django 5.1.7 on 2025-05-15 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_userreference_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='rollover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='thresholds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='budget_app.userreference'),
            preserve_default=False,
        ),
    ]
